home:
  Home: /

links:
  Links: links

about:
  About: about

copyright:
  name: wolfyzhang

license:
  name: CC-BY-NC-SA 4.0
  url: https://creativecommons.org/licenses/by-nc-sa/4.0/

favicon: favicon.ico

mathjax:
  enable: false
  # cnd: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.min.js

# KaTeX
# 使用 KaTeX 需要移除默认的渲染器：
# $ npm uninstall hexo-renderer-marked --save
# 然后安装：
# $ npm install @upupming/hexo-renderer-markdown-it-plus --save
# 安装完成后执行清理命令：
# $ hexo clean
katex:
  enable: true
  cdn: https://cdn.jsdelivr.net/npm/katex@0/dist/katex.min.css

analytics:
  genable: true
  benable: true
  gtag: G-P8TPGHN83M
  btag: 814574df4ca5d3c5a44b815c9ad229ef

symbols_count_time:
  symbols: true
  time: false
  total_symbols: true
  total_time: false
  exclude_codeblock: false
  wpm: 275
  suffix: "mins."
