favicon: images/avatar.png

home:
  主页: /

about:
  关于: about

copyright:
  name: wolfyzhang

license:
  name: CC-BY-NC-SA 4.0
  url: https://creativecommons.org/licenses/by-nc-sa/4.0/

mathjax:
  enable: false
  # cnd: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.min.js

# KaTeX
# 使用 KaTeX 需要移除默认的渲染器：
# $ npm uninstall hexo-renderer-marked --save
# 然后安装：
# $ npm install @upupming/hexo-renderer-markdown-it-plus --save
# 安装完成后执行清理命令：
# $ hexo clean
katex:
  enable: true
  cdn: https://cdn.jsdelivr.net/npm/katex@0/dist/katex.min.css